version: '3.8'

services:

#  phexpedition:
#    container_name: phexpedition
#    image: bjblazko/phexpedition:latest
#    environment:
#    - 'quarkus.banner.enabled=false'
#    - 'quarkus.log.console.json=true'
#    - 'quarkus.log.level=INFO'
#    - 'quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/phexpedition'
#    - 'quarkus.datasource.username=phexpedition'
#    - 'quarkus.datasource.password=test'
#    ports:
#    - "8080:8080"
#    depends_on:
#      - postgres

  postgres:
    container_name: postgres
    image: library/postgres:12.4-alpine
    restart: always
    environment:
      POSTGRES_DB: phexpedition
      POSTGRES_USER: phexpedition
      POSTGRES_PASSWORD: test
    ports:
    - "5432:5432"
