version: '3.1'

networks:
  backend:
    driver: "bridge"

services:

  phexpedition:
    image: bjblazko/phexpedition:latest
    environment:
      - 'quarkus.log.console.json=true'
      - 'quarkus.datasource.db-kind=postgresql'
      - 'quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/test'
      - 'quarkus.datasource.username=test'
      - 'quarkus.datasource.password=test'
    ports:
    - "8080:8080"
    networks:
      backend:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
    - "5432:5432"
    networks:
      backend:
