global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'host.docker.internal:8080'
          - 'postgres-prometheus-exporter:9187'
          - 'prometheus:9090'
