# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# Maven/Cache/Docker stuff taken from https://medium.com/@alexander.volminger/ci-cd-for-java-maven-using-github-actions-d009a7cb4b8f

name: Docker Hub image

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: mvn -B package --file pom.xml
      - run: mkdir staging && cp target/webapp-*runner.jar staging/phexpedition-webapp.jar
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging
      - name: Docker - build image
        run: docker build --tag phexpedition:$GITHUB_RUN_NUMBER --tag phexpedition:latest --file src/main/docker/Dockerfile.jvm .
      - name: Docker - login
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.HEROKU_API_KEY}} ${{secrets.DOCKER_REPO}}
      - name: Docker - upload to repository
        run: docker push phexpedition
